### ISSUE TITLE
Pojo to raml fails to convert pojo that contains enum

### ISSUE THREAD

**Issue by vrozkovec** [mulesoft-labs/raml-java-tools#23]
If you add SimpleEnum to the pojo-to-raml/src/test/java/org/raml/pojotoraml/Fun.java and run tests, it fails:

```
org.raml.builder.ModelBuilderException: model errors: Invalid reference 'SimpleEnum'
	at org.raml.builder.Util$2.apply(Util.java:129)
	at org.raml.builder.Util.buildModel(Util.java:62)
	at org.raml.builder.RamlDocumentBuilder.buildModel(RamlDocumentBuilder.java:108)
	at org.raml.pojotoraml.PojoToRamlImplTest.createApi(PojoToRamlImplTest.java:155)
	at org.raml.pojotoraml.PojoToRamlImplTest.simpleStuff(PojoToRamlImplTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

Is this expected behavior? This way I cannot convert any pojo, that contains Enum.

**Comment by jpbelang** [comment]
I've fixed this on release/1.0.6.

**Comment by vrozkovec** [comment]
Thank you for a quick reply, I had also problem with a Map<String, String>.

**Comment by jpbelang** [comment]
Is this for jackson's @JsonAnyGetter ?  RAML does not support Map types as such.

**Comment by jpbelang** [comment]
There is an example there in the org.raml.pojotoraml.PojoToRamlImplTest.  It's not entirely complete, but it's decent.

**Comment by vrozkovec** [comment]
Hi, thanks for the update. However, after trying I've resorted to going different route, Pojo -> JSON schema -> Raml, I couldn't just throw any POJO at the parser to get proper Raml type. A bit more work but I need JSON Schema for our app developer anyway, so that's fine.
